# keep theme
base_info:
  title: 一颗栗子球
  author: cyoahs
  url: http://shaoyecheng.com/

style:
  avatar: /keep/images/avatar.png
  favicon: /keep/images/avatar.png

  # Article image align position, value: left | center
  article_img_align: left

  # Left side width
  left_side_width: 260px

  # Content area max width
  content_max_width: 920px

  # Mouse hover
  hover:
    shadow: true # shadow effect when the mouse hover
    scale: true # scale effect when the mouse hover

  # First screen
  first_screen:
    enable: true
    background_img: /images/bg.svg # You can use local image or image external link
    description: |
            在我自己的杯中，饮了我的酒吧，朋友。
            一倒在别人的杯里，这酒的腾跳的泡沫便要消失了。

  # Scroll style settings
  scroll:
    progress_bar:
      enable: false
    percent:
      enable: true

post:
  author_label:
    enable: false
    auto: true  # if true, show Lv1, Lv2, Lv3... , If false, show custom label
    # label array item can be one or more
    custom_label_list: [ "Trainee", "Engineer", "Architect", "CTO", "BOSS" ]

social_contact:
  enable: true
  links:
    github: https://github.com/cyoahs
    zhihu: https://www.zhihu.com/people/shao-ye-cheng
    email: shaoyecheng@zju.edu.cn

menu:
  Home: /
  Archives: /archives

home_article:
  category:
    enable: false     # show category in home page article block
    limit: 10          # max number of categories shown in home page article block
  tag:
    enable: true     # show tags in home page article block
    limit: 5          # max number of tags shown in home page article block

toc:
  enable: true

  # Automatically add list number to toc.
  number: true

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: false

  # If true, open TOC every time when you enter the article page
  init_open: true

footer:
  since: 2018
  icp: 浙ICP备18032789号-1             # ICP record number of your website, Can be null

